### Loading Needed Data

In [59]:
X = np.array([
    #      big matrix for all the different characters

    #
    [ # character, index: A, 0
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # character, index: B, 1
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [ # character, index: C, 2
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 1]
    ],

    [ # char, i: D, 3
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [
        # char, i: E, 4
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],

    [ # char, i: F, 5
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]
    ],

    [ # char, i: G, 6
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [ # char H
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # char I
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # char J
        [0, 0, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 1, 0],
        [1, 0, 1, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 0, 1, 0, 0],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 0, 1]
    ],

    [
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 0, 1, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 0, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 0, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]
    ],

    [ # Q
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 1, 0],
        [1, 1, 1, 0, 1]
    ],

    [ # char, i: R, 5
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # character, index: S, 2
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [ # char T
        [1, 1, 1, 1, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # char U
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [ # char V
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # char W
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 1, 0, 1, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # char H
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # Z i = 25
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],


    [ # blank i = 26
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],

    [ # a = 27
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1]
    ],

    [ # b = 28
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [ # c = 29
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 1]
    ],

    [ # d = 30
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1]
    ],

    [ # e = 31
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 0, 1, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0]
    ],

    [ # g = 33
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # i = 35
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 1, 0, 0]
    ],

    [ # k
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 1, 0],
        [1, 1, 1, 0, 0],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 0, 1]
    ],

    [ # l
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0]
    ],

    [ # m
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1]
    ],

    [ # n
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # o
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [ # p
        [0, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]
    ],

    [ # q
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1]
    ],

    [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]
    ],

    [ # s
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [ # t
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]
    ],

    [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # w
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [0, 1, 0, 1, 0]
    ],

    [ # x
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 1, 0],
        [1, 0, 0, 0, 1]
    ],

    [ # y
        [0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],

    [ # 0
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 1, 1],
        [1, 0, 1, 0, 1],
        [1, 1, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 0, 1, 0, 0],
        [0, 1, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],

    [
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1]
    ],

    [ # 5
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],


    [
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ]

])


print(X[53])

[[0 1 1 1 0]
 [1 0 0 0 1]
 [1 0 0 1 1]
 [1 0 1 0 1]
 [1 1 0 0 1]
 [1 0 0 0 1]
 [0 1 1 1 0]]


In [97]:
# defining all the needed functions
def string_to_index(string):
    ascii = [ord(string[i]) for i in range(len(string))]
    index = []
    # convert from my data to ascii
    for k in range(len(ascii)):
      # lower case letters a-z
      if 97 <= ascii[k] and ascii[k] <= 122:
        index.append(ascii[k]-97+27)
      # upper case letters A-Z
      elif 65 <= ascii[k] and ascii[k] <= 90:
        index.append(ascii[k]-65)
      elif 48 <= ascii[k] and ascii[k] <= 57:
        index.append(ascii[k]-48+27+26)
      elif ascii[k] == 32:
        index.append(26)
      # if can't find anything, return 999
      else:
        index.append(999)
    return index

def index_to_matrix(index,dataset):
    s = []
    # Python lists need copying
    data = dataset.copy()
    for i in range(len(index)):
      matrix = data[index[i]]
      s.append(matrix)

    return s

def string_to_matrix(string):
    return index_to_matrix(string_to_index(string), X)

print(string_to_index(';'))

[999]


In [62]:
from IPython.display import display
from ipywidgets import widgets
from ipywidgets import GridspecLayout, Layout
import numpy as np
import functools

# set up some display values
max_str_length = 10

# grid cell color
bgcolor_selected ='green'
bgcolor_unselected = 'black'

# grid size (7x5)
n_rows = 7
n_cols = 5

# create a text box to input a new string
text = widgets.Text(
                    value='WELCOME',
                    placeholder='Type something',
                    description='Enter Here:',
                    disabled=False
                )

# create a clear button to empty all grid cells
btn_clear = widgets.Button(description = 'Clear')

# create a clear button to empty all grid cells
btn_display = widgets.Button(description = 'Display')

# create a noisy button to empty all grid cells
btn_noise = widgets.Button(description = 'Noise')

# create a matrix for each character in text.value
chars = [np.zeros((n_rows, n_cols)) for i in range(max_str_length)]

# create a grid to accommodate 7 x 5 buttons
grid = [GridspecLayout(n_rows, n_cols, width='200px', layout=Layout(grid_gap='0px 0px')) for i in range(max_str_length)]

# create 7 x 5 buttons (each button denotes one pixel)
buttons = [[[widgets.Button(description = '',
                           layout = Layout(width='25px', height='25px', border='3px solid gray'))
                           for j in range(n_cols)] for i in range(n_rows)] for i in range(max_str_length)]

g2 = widgets.HBox([grid[i] for i in range(max_str_length)])

for k in range(max_str_length):
    for i in range(n_rows):
        # change the text area
        for j in range(n_cols):
            if chars[k][i,j] == 1:
              buttons[k][i][j].style.button_color = bgcolor_selected
            else:
              buttons[k][i][j].style.button_color = bgcolor_unselected
            # this links the grid and buttons - only need to do this once?
            grid[k][i, j] = buttons[k][i][j]

# arrange our GUI elements
g1 = widgets.VBox([btn_display, btn_clear, btn_noise])
g3 = widgets.VBox([text,g1,g2])

def on_display_clicked():
    global chars
    # get the new matricies to display
    chars = string_to_matrix(text.value)
    for k in range(len(text.value)):
      for i in range(n_rows):
          for j in range(n_cols):
              if chars[k][i,j] == 1:
                buttons[k][i][j].style.button_color = bgcolor_selected
              else:
                buttons[k][i][j].style.button_color = bgcolor_unselected

# define what happens when display button is clicked
def on_btn_display_clicked(_):
    on_display_clicked()

# define what happens when the clear button is clicked
def on_btn_clear_clicked(_):
    global chars
    chars = [np.zeros((n_rows, n_cols)) for i in range(max_str_length)]
    for k in range(max_str_length):
      for i in range(n_rows):
          for j in range(n_cols):
                buttons[k][i][j].style.button_color = bgcolor_unselected

def on_noise_clicked():
    global chars
    # get the new matricies to display
    chars = string_to_matrix(text.value)
    for k in range(len(text.value)):
      for i in range(n_rows):
          for j in range(n_cols):
              if chars[k][i,j] == 1:
                buttons[k][i][j].style.button_color = bgcolor_selected
              elif np.random.choice([0,1],p=[9/10,1/10]) == 1:
                chars[k][i,j] = 1
                buttons[k][i][j].style.button_color = bgcolor_selected
              else:
                buttons[k][i][j].style.button_color = bgcolor_unselected

def on_btn_noise_clicked(_):
    on_noise_clicked()

# bind the noise event to the noise buttonn
btn_noise.on_click(on_btn_noise_clicked)

# bind the display event to the display button
btn_display.on_click(on_btn_display_clicked)

# bind the click event to the clear button
btn_clear.on_click(on_btn_clear_clicked)

display(g3)

## Building Neural Network

In [8]:
# Import the Perceptron class from scikit-learn's linear_model module
from sklearn.linear_model import Perceptron

Define target labels

In [70]:
# We already have data X, now create our target array y which matches with the indicies of our data array

upper = np.array([chr(i) for i in range(65,91)])
space = [chr(32)]
lower = np.array([chr(i) for i in range(97,123)])
numbr = np.array([chr(i) for i in range(48,58)])
y = np.concatenate((upper,space,lower,numbr))
print(y)
print(len(y))

print(y[57])
print(X[57])

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z' ' ' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i'
 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z' '0'
 '1' '2' '3' '4' '5' '6' '7' '8' '9']
63
4
[[1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]]


## Sampling

We need to create some data to train our network on! Note that for perceptron to work, we need to flatten our $7\times 5$ display matricies to $1 \times 35$ vectors to get a 2d problem.

In [71]:
def gen_noisy_char(character):
    s = string_to_matrix(character)[0]
    for i in range(n_rows):
      for j in range(n_cols):
        if s[i][j] != 1:
          s[i][j] = np.random.choice([1,0],p=[1/10,9/10])

    #return s.flatten()
    return s


def create_data(data_size):
    # create some random indicies to aim for (our y vector)
    random_indicies = np.random.choice(len(X),data_size)

    y_dataset = y[random_indicies]
    X_dataset = np.asarray([gen_noisy_char(y_dataset[i]) for i in range(data_size)])

    nsamples, nx, ny = X_dataset.shape
    d2_X_dataset = X_dataset.reshape((nsamples,nx*ny))

    return d2_X_dataset, y_dataset

data_size = 1000

X_dataset, y_dataset = create_data(data_size)

print(y_dataset)
print(X_dataset)
print(y_dataset.shape)
print(X_dataset.shape)

['3' 'I' 'U' '6' '9' 'D' 'g' 'T' 'T' 'I' '5' '7' 's' 'V' 'C' 's' '5' '3'
 '7' 'K' 'r' 'A' 'H' 'X' '9' 't' '7' 'D' 'i' 'I' 'b' '8' 'C' '9' 'k' 'V'
 'h' 'Q' 'Q' 'w' ' ' 'A' 't' 'i' 'b' 'k' '3' 'x' 'J' 'm' 'u' 'V' 'Z' 'H'
 'W' '3' '7' '0' 'p' 'd' 'J' 'd' 'O' 'J' 'N' 'F' 'w' ' ' 'H' 't' 'p' 'L'
 'f' 'F' 'H' 'J' 'P' '2' 'c' 'B' 'Q' 'u' 'c' 'D' '5' 'r' '2' 'u' 'u' 'j'
 'c' 'P' 'f' 'h' 'n' 'A' 'V' 'g' 'a' 's' 'f' 'S' 'M' 'x' 'q' 'c' 'n' '8'
 'h' 'R' 'Z' 'g' 'C' '6' 'e' '3' 'd' 'E' 'l' 'n' 'S' 'a' '8' '8' '9' 'w'
 'Y' 'z' 's' 'z' 'S' 'E' 'i' 'Y' 'A' 's' '1' 'U' 'L' 'l' 'F' 'h' 'g' '0'
 'Y' 'a' 'z' 'Q' '7' 'Q' 'J' '4' 'N' 'v' 'M' 'c' 'l' 'C' 'i' 'm' 'y' 'H'
 'a' 'g' 'r' 'V' 'w' 'f' '7' 'R' '5' 'q' 'T' 'S' 'S' 'y' 'k' 'X' 'D' '2'
 'V' 'f' 'L' 'U' 'b' 'O' 'Y' 'C' 'g' 'r' '2' 'q' 'g' 'Q' '4' 'Q' 'd' '9'
 'b' 'J' '2' 'W' '0' 'W' 'z' 'w' 'z' 'd' 'l' 'Z' 'S' '7' 'p' 'Z' 'n' '5'
 '4' 'L' 'B' 'n' 'w' 'i' 'Q' '0' 'o' 'D' 'k' 'T' 'Y' 'g' '7' 'r' 'o' 's'
 'P' 'o' ' ' 'Y' 'g' 'I' 'c' '1' 'K' 'U' 's' 'U' '9

### test train split

In [72]:
# Import the train_test_split function from scikit-learn's model_selection module
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_dataset, y_dataset, test_size=0.1)

print(X_train.shape)
print(y_train.shape)



(900, 35)
(900,)


### Training


In [73]:
from sklearn.linear_model import Perceptron
perceptron_model = Perceptron(max_iter=100)

perceptron_model.fit(X_train, y_train)



Perceptron(max_iter=100)

In [74]:
#  printing the learned weights (coefficients) of the Perceptron model
print("Weights (coefficients):")
print(perceptron_model.coef_)

# printing the learned bias (intercept) of the Perceptron model
print("Bias (intercept):")
print(perceptron_model.intercept_)

Weights (coefficients):
[[-1. -1. -3. ...  0.  0.  0.]
 [-3.  3.  1. ... -3. -1. -4.]
 [-6. -1.  1. ...  3. -5. -4.]
 ...
 [-3. -2. -3. ... -4. -4.  2.]
 [-1. -2. -4. ...  1.  3. -5.]
 [-1. -3. -3. ...  2.  3.  0.]]
Bias (intercept):
[  4.  -9. -11.  -5.  -5.  -6. -20. -31.  -3. -11. -11. -10. -34.  -3.
 -15. -12.  -4.  -5. -20. -10.  -3.  -5.  -4. -14.  -8. -15.  -4.  -7.
 -16.  -4.  -8. -12.  -3. -11.  -2.  -3.  -4.  -4.  -5.  -3.  -9.  -4.
  -3. -18.  -4.  -2.  -2.  -8.  -6.  -5.  -2.  -3.  -2.  -4.  -2.  -5.
  -5.  -5.  -4.  -9.  -4.  -3.  -4.]


In [75]:
# TODO: Add a line of code to make predictions on the input features (X), using the trained Perceptron model.
y_pred = perceptron_model.predict(X_test)

# Print the predictions and model parameters
print("Input Features:")
print(X_test)
print("\nTrue Labels:")
print(y_test)
print("\nPredictions:")
print(y_pred)

Input Features:
[[0 1 1 ... 1 1 0]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 1 0]
 ...
 [1 1 1 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]]

True Labels:
['S' 'd' 'S' 'u' '8' '8' 'm' 'g' 'F' 'B' 'f' 'x' 'O' 'D' 'j' 'a' 'Z' 'b'
 'X' 'O' 'h' 'S' 'L' 'c' 'e' 'q' '6' 'Y' 'I' 'B' 'l' 'd' '2' 'w' 'L' '0'
 'C' 'H' '4' 'g' 's' 'F' 'W' 's' 'Y' 'b' 'O' '8' 'i' '1' 'v' 'X' 'W' 'Z'
 'c' 'X' 'g' 'X' 'z' 'v' 'E' 'V' 'h' 'n' 'z' 'I' 'D' 'G' 'O' 'Z' 'q' 'i'
 'C' 'K' 'A' 'd' 'M' 'u' 'q' 'N' '8' 'R' 'b' 'z' '0' '6' 'W' 'o' ' ' 'w'
 '3' 'D' '1' '1' 'R' 'f' ' ' 'B' 'u' ' ']

Predictions:
['S' 'd' 'S' 'u' '8' '8' 'm' 'g' 'F' '3' 'f' 'x' 'O' 'O' 'j' 'a' 'Z' 'b'
 'X' 'O' 'h' '8' 'L' 'c' 'e' 'q' '6' 'Y' 'I' '6' 'l' 'M' '2' 'w' 'L' '0'
 'C' 'H' '4' 'g' 's' 'F' 'W' 's' 'Y' 'b' 'G' '8' 'i' '1' 'v' 'X' 'W' 'Z'
 'c' 'X' 'g' 'X' 'z' 'v' 'E' 'V' 'h' 'n' 'z' 'I' 'O' 'G' 'O' 'Z' 'q' 'i'
 'C' 'K' 'A' 'd' 'M' 'u' 'q' 'X' '8' 'R' 'b' 'z' '0' '6' 'W' 'o' ' ' 'w'
 '3' 'O' '1' 'I' 'R' 'f' 'N' '3' 'u' ' ']


## catching bad user inputs

In [85]:
import re

input_str = input("Please provide some info: ")
if not (re.match("^[a-z]*$", input_str) or re.match("^[A-Z]*$", input_str)) or re.match("^[0-9]*$", input_str):
    print("Error! Only letters A-Z, a-z and 0-9 allowed!")

elif len(input_str) > 15:
    print("Error! Only 15 characters allowed!")


print("Your input was:", input_str)

Please provide some info: h
Your input was: h


# Adding NN into GUI

In [87]:
from IPython.display import display
from ipywidgets import widgets
from ipywidgets import GridspecLayout, Layout
import numpy as np
import functools

# set up some display values
max_str_length = 10

# grid cell color
bgcolor_selected ='green'
bgcolor_unselected = 'black'

# grid size (7x5)
n_rows = 7
n_cols = 5

# create a text box to input a new string
text = widgets.Text(
                    value='WELCOME',
                    placeholder='Type something',
                    description='Enter Here:',
                    disabled=False
                )

# create a clear button to empty all grid cells
btn_clear = widgets.Button(description = 'Clear')

# create a clear button to empty all grid cells
btn_display = widgets.Button(description = 'Display')

# create a noisy button to empty all grid cells
btn_noise = widgets.Button(description = 'Noise')

# create a predict button
btn_predict = widgets.Button(description = 'Predict')

# create a text area to display the prediction
prediction_box = widgets.Textarea(value='',
                       placeholder='Perceptron Guesses...',
                       description='',
                       layout=widgets.Layout(height="120px", width="300px"))

# create a matrix for each character in text.value
chars = [np.zeros((n_rows, n_cols)) for i in range(max_str_length)]

# create a grid to accommodate 7 x 5 buttons
grid = [GridspecLayout(n_rows, n_cols, width='200px', layout=Layout(grid_gap='0px 0px')) for i in range(max_str_length)]

# create 7 x 5 buttons (each button denotes one pixel)
buttons = [[[widgets.Button(description = '',
                           layout = Layout(width='25px', height='25px', border='3px solid gray'))
                           for j in range(n_cols)] for i in range(n_rows)] for i in range(max_str_length)]

g2 = widgets.HBox([grid[i] for i in range(max_str_length)])

for k in range(max_str_length):
    for i in range(n_rows):
        # change the text area
        for j in range(n_cols):
            if chars[k][i,j] == 1:
              buttons[k][i][j].style.button_color = bgcolor_selected
            else:
              buttons[k][i][j].style.button_color = bgcolor_unselected
            # this links the grid and buttons - only need to do this once?
            grid[k][i, j] = buttons[k][i][j]

# arrange our GUI elements
g1 = widgets.VBox([btn_display, btn_clear, btn_noise, btn_predict])
g3 = widgets.VBox([text,g1,g2,prediction_box])

def catch_input_too_long(string):
    if len(string) > max_str_length:


def on_display_clicked():
    global chars
    # get the new matricies to display

    chars = string_to_matrix(text.value)
    for k in range(len(text.value)):
      for i in range(n_rows):
          for j in range(n_cols):
              if chars[k][i,j] == 1:
                buttons[k][i][j].style.button_color = bgcolor_selected
              else:
                buttons[k][i][j].style.button_color = bgcolor_unselected

# define what happens when display button is clicked
def on_btn_display_clicked(_):
    on_display_clicked()

# define what happens when the clear button is clicked
def on_btn_clear_clicked(_):
    global chars
    prediction_box.value = 'Perceptron Guesses...'
    chars = [np.zeros((n_rows, n_cols)) for i in range(max_str_length)]
    for k in range(max_str_length):
      for i in range(n_rows):
          for j in range(n_cols):
                buttons[k][i][j].style.button_color = bgcolor_unselected

def on_noise_clicked():
    global chars
    # get the new matricies to display
    chars = string_to_matrix(text.value)
    for k in range(len(text.value)):
      for i in range(n_rows):
          for j in range(n_cols):
              if chars[k][i,j] == 1:
                buttons[k][i][j].style.button_color = bgcolor_selected
              elif np.random.choice([0,1],p=[9/10,1/10]) == 1:
                chars[k][i,j] = 1
                buttons[k][i][j].style.button_color = bgcolor_selected
              else:
                buttons[k][i][j].style.button_color = bgcolor_unselected

def on_predict_clicked():

    # reshape chars to 2d
    data = np.asarray(chars)
    nsamples, nx, ny = data.shape
    chars_formatted = data.reshape((nsamples,nx*ny))

    # predict the outcome
    prediction = perceptron_model.predict(chars_formatted)

    # reformat as a string and output
    output = ''.join([str(elem) for elem in prediction])
    prediction_box.value = output


def on_btn_noise_clicked(_):
    on_noise_clicked()

def on_btn_predict_clicked(_):
    on_predict_clicked()

# bind the noise event to the noise button
btn_noise.on_click(on_btn_noise_clicked)

# bind the display event to the display button
btn_display.on_click(on_btn_display_clicked)

# bind the clear event to the clear button
btn_clear.on_click(on_btn_clear_clicked)

# bind the predict event to the predict button
btn_predict.on_click(on_btn_predict_clicked)

display(g3)

IndentationError: expected an indented block after 'if' statement on line 73 (<ipython-input-87-d944387472b0>, line 76)

## adding in error handling

In [110]:
from IPython.display import display
from ipywidgets import widgets
from ipywidgets import GridspecLayout, Layout
import numpy as np
import functools

# set up some display values
max_str_length = 10

# grid cell color
bgcolor_selected ='green'
bgcolor_unselected = 'black'

# grid size (7x5)
n_rows = 7
n_cols = 5

# create a text box to input a new string
text = widgets.Text(
                    value='WELCOME',
                    placeholder='Type something',
                    description='Enter Here:',
                    disabled=False,
                    layout=Layout(width='50%', height='80px')
                )

# create a clear button to empty all grid cells
btn_clear = widgets.Button(description = 'Clear Matrix Display',
                                layout = Layout(width='50%', height='80px'))

# create a clear button to empty all grid cells
btn_display = widgets.Button(description = 'Show Original Matrix Display',
                                  layout = Layout(width='50%', height='80px'))

# create a noisy button to empty all grid cells
btn_noise = widgets.Button(description = 'Show Noisy Matrix Display',
                                layout = Layout(width='50%', height='80px'))

# create a predict button
btn_predict = widgets.Button(description = 'Predict Noisy Matrix Display',
                                  layout = Layout(width='50%', height='80px'))

# create a text area to display the prediction
prediction_box = widgets.Textarea(value='',
                       placeholder='Perceptron Guesses...',
                       description='',
                       layout=widgets.Layout(height="120px", width="300px"))

# create a matrix for each character in text.value
chars = [np.zeros((n_rows, n_cols)) for i in range(max_str_length)]

# create a grid to accommodate 7 x 5 buttons
grid = [GridspecLayout(n_rows, n_cols, width='200px', layout=Layout(grid_gap='0px 0px')) for i in range(max_str_length)]

# create 7 x 5 buttons (each button denotes one pixel)
buttons = [[[widgets.Button(description = '',
                           layout = Layout(width='25px', height='25px', border='3px solid gray'))
                           for j in range(n_cols)] for i in range(n_rows)] for i in range(max_str_length)]

g2 = widgets.HBox([grid[i] for i in range(max_str_length)])

for k in range(max_str_length):
    for i in range(n_rows):
        # change the text area
        for j in range(n_cols):
            if chars[k][i,j] == 1:
              buttons[k][i][j].style.button_color = bgcolor_selected
            else:
              buttons[k][i][j].style.button_color = bgcolor_unselected
            # this links the grid and buttons - only need to do this once?
            grid[k][i, j] = buttons[k][i][j]

# arrange our GUI elements
g1 = widgets.VBox([btn_display, btn_clear, btn_noise, btn_predict])
g3 = widgets.VBox([text,g1,g2,prediction_box])

# catching errors in the input:
def input_check(input):
    if len(input) > max_str_length:
      return 'Input too long, try again'
    for k in range(len(input)):
      if string_to_index(input[k]) == [999]:
        return 'Digit "' + input[k] + '" not recognised, try another input'
    else:
      return 'error'


def on_display_clicked():
    global chars
    # get the new matricies to display
    try:
      chars = string_to_matrix(text.value)
      for k in range(len(text.value)):
        for i in range(n_rows):
            for j in range(n_cols):
                if chars[k][i,j] == 1:
                  buttons[k][i][j].style.button_color = bgcolor_selected
                else:
                  buttons[k][i][j].style.button_color = bgcolor_unselected
    except:
      prediction_box.value = input_check(text.value)

# define what happens when display button is clicked
def on_btn_display_clicked(_):
    on_display_clicked()


# define what happens when the clear button is clicked
def on_btn_clear_clicked(_):
    global chars
    prediction_box.value = 'Perceptron Guesses...'
    chars = [np.zeros((n_rows, n_cols)) for i in range(max_str_length)]
    for k in range(max_str_length):
      for i in range(n_rows):
          for j in range(n_cols):
                buttons[k][i][j].style.button_color = bgcolor_unselected

def on_noise_clicked():
    global chars
    # get the new matricies to display
    try:
      chars = string_to_matrix(text.value)
      for k in range(len(text.value)):
        for i in range(n_rows):
            for j in range(n_cols):
                if chars[k][i,j] == 1:
                  buttons[k][i][j].style.button_color = bgcolor_selected
                elif np.random.choice([0,1],p=[9/10,1/10]) == 1:
                  chars[k][i,j] = 1
                  buttons[k][i][j].style.button_color = bgcolor_selected
                else:
                  buttons[k][i][j].style.button_color = bgcolor_unselected
    except:
      prediction_box.value = input_check(text.value)


def on_predict_clicked():

    try:
      # reshape chars to 2d
      data = np.asarray(chars)
      nsamples, nx, ny = data.shape
      chars_formatted = data.reshape((nsamples,nx*ny))

      # predict the outcome
      prediction = perceptron_model.predict(chars_formatted)

      # reformat as a string and output
      output = ''.join([str(elem) for elem in prediction])
      prediction_box.value = output
    except:
      prediction_box.value = input_check(text.value)


def on_btn_noise_clicked(_):
    on_noise_clicked()

def on_btn_predict_clicked(_):
    on_predict_clicked()

# bind the noise event to the noise button
btn_noise.on_click(on_btn_noise_clicked)

# bind the display event to the display button
btn_display.on_click(on_btn_display_clicked)

# bind the clear event to the clear button
btn_clear.on_click(on_btn_clear_clicked)

# bind the predict event to the predict button
btn_predict.on_click(on_btn_predict_clicked)

display(g3)

In [105]:
# catching errors in the input:
def input_check(input):
    if len(input) > max_str_length:
      return 'Input too long, try again'
    for k in range(len(input)):
      print(string_to_index(input[k]))
      if string_to_index(input[k]) == [999]:
        print("BAD!")
        return 'Digit ' + input[k] + ' not recognised'
    else:
      return 'error'

print(input_check('?'))

[999]
BAD!
Digit? not recognised
