# Neural Computing Coursework
My code for question 1 is below. My written solutions to question 2 and 3 can be accessed via this link: [click me!](https://drive.google.com/file/d/13i7eH7OUaXBlLQpelFhl-KEkjUbL8-qw/view?usp=sharing)

## Question 1

Train a neural network to recognise a 7x5 matrix display of digital letters (A-Z, a-z) and numerals
(0-9). Build a graphical user interface (GUI), which allows users to enter a
string (e.g., “WELCOME”) for testing.
Specifically, you are required to



1.   create a textbox to enter a testing string (e.g. “WELCOME”);
2.   create a button with caption “Show Original Matrix Display”. When the button is clicked,
visualise the original 7x5 matrix display for each character of your typed string;
3. create a button with caption “Show Noisy Matrix Display”. When the button is clicked, add 10% noisy pixels at random to each original 7x5 matrix display obtained in step (1) first and then visualise each perturbed 7x5 matrix display after noise is added.
4. create a button with caption “Predict Noisy Matrix Display”. When the button is clicked,
train your network and label the predicted character for each noisy 7x5 matrix display obtained in step (3).

## Solution

First, let's import all the libraries we'll need. This includes the `Perceptron` class from scikit-learn's `linear_model module`.

In [50]:
from IPython.display import display
from ipywidgets import widgets
from ipywidgets import GridspecLayout, Layout
import numpy as np
from sklearn.linear_model import Perceptron

### Defining Input Features

First, we'll need to define the matrices that will represent all of the characters in grid form. This is our data `X`.

In [51]:
X = np.array([
    #      big matrix for all the different characters

    #
    [ # character, index: A, 0
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # character, index: B, 1
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [ # character, index: C, 2
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 1]
    ],

    [ # char, i: D, 3
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [
        # char, i: E, 4
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],

    [ # char, i: F, 5
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]
    ],

    [ # char, i: G, 6
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [ # char H
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # char I
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # char J
        [0, 0, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 1, 0],
        [1, 0, 1, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 0, 1, 0, 0],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 0, 1]
    ],

    [
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 0, 1, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 0, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 0, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]
    ],

    [ # Q
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 1, 0],
        [1, 1, 1, 0, 1]
    ],

    [ # char, i: R, 5
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # character, index: S, 2
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [ # char T
        [1, 1, 1, 1, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # char U
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [ # char V
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # char W
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 1, 0, 1, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # char H
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # Z i = 25
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],


    [ # blank i = 26
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],

    [ # a = 27
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1]
    ],

    [ # b = 28
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [ # c = 29
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 1]
    ],

    [ # d = 30
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1]
    ],

    [ # e = 31
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 0, 1, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0]
    ],

    [ # g = 33
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # i = 35
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 1, 0, 0]
    ],

    [ # k
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 1, 0],
        [1, 1, 1, 0, 0],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 0, 1]
    ],

    [ # l
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0]
    ],

    [ # m
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1]
    ],

    [ # n
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1]
    ],

    [ # o
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [ # p
        [0, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]
    ],

    [ # q
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1]
    ],

    [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]
    ],

    [ # s
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [ # t
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 1]
    ],

    [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0]
    ],

    [ # w
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1],
        [0, 1, 0, 1, 0]
    ],

    [ # x
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 1, 0],
        [1, 0, 0, 0, 1]
    ],

    [ # y
        [0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],

    [ # 0
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 1, 1],
        [1, 0, 1, 0, 1],
        [1, 1, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 0, 1, 0, 0],
        [0, 1, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ],

    [
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1]
    ],

    [ # 5
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],

    [
        [1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 0]
    ],


    [
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]
    ],

    [
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ],

    [
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [0, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 1, 1, 0]
    ]

])

# Print the first character 'A'
print(X[0])

[[0 1 1 1 0]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]]


### Accessing data `X`

We need to create some functions to translate between user inputted strings, the ASCII representation of each character and the data in matrix form.

In [52]:
# defining all the needed functions
def string_to_index(string):
    ascii = [ord(string[i]) for i in range(len(string))]
    index = []
    # convert from my data to ascii
    for k in range(len(ascii)):
      # lower case letters a-z
      if 97 <= ascii[k] and ascii[k] <= 122:
        index.append(ascii[k]-97+27)
      # upper case letters A-Z
      elif 65 <= ascii[k] and ascii[k] <= 90:
        index.append(ascii[k]-65)
      elif 48 <= ascii[k] and ascii[k] <= 57:
        index.append(ascii[k]-48+27+26)
      elif ascii[k] == 32:
        index.append(26)
      # if can't find anything, return 999
      else:
        index.append(999)
    return index

def index_to_matrix(index,dataset):
    s = []
    # Python lists need copying
    data = dataset.copy()
    for i in range(len(index)):
      matrix = data[index[i]]
      s.append(matrix)

    return s

def string_to_matrix(string):
    return index_to_matrix(string_to_index(string), X)

# note that characters not in dataset X throw an error '999'
print(string_to_index(';'))

[999]


## Building the Neural Network

We can now create our target labels $y$.

In [53]:
# We already have data X, now create our target array y which matches with the indicies of our data array

upper = np.array([chr(i) for i in range(65,91)])
space = [chr(32)]
lower = np.array([chr(i) for i in range(97,123)])
numbr = np.array([chr(i) for i in range(48,58)])

# this is our feature
y = np.concatenate((upper,space,lower,numbr))
print(y, "\n")

# the matrix representation agrees with the character representation
print(y[57])
print(X[57])

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z' ' ' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i'
 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z' '0'
 '1' '2' '3' '4' '5' '6' '7' '8' '9'] 

4
[[1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]]


### Sampling

We need to create some noisy matrix data that we can use to train our Perceptron. Note that because our matricies are of dimension $7\times5$, this creates 3 dimensional training data. The perceptron only accepts data of dimension 2, so we must flatten our matrix to a vector of length $1\times 35$.

In [54]:
# grid size (7x5)
n_rows = 7
n_cols = 5

def gen_noisy_char(character):
    s = string_to_matrix(character)[0]
    for i in range(n_rows):
      for j in range(n_cols):
        if s[i][j] != 1:
          s[i][j] = np.random.choice([1,0],p=[1/10,9/10])
    return s


def create_data(data_size):
    # create some random indicies to aim for (our y vector)
    random_indicies = np.random.choice(len(X),data_size)

    y_dataset = y[random_indicies]
    X_dataset = np.asarray([gen_noisy_char(y_dataset[i]) for i in range(data_size)])

    nsamples, nx, ny = X_dataset.shape
    d2_X_dataset = X_dataset.reshape((nsamples,nx*ny))

    return d2_X_dataset, y_dataset

data_size = 10

X_dataset, y_dataset = create_data(data_size)

print(y_dataset)
print(X_dataset)

data_size = 1000

X_dataset, y_dataset = create_data(data_size)

['O' 'W' 'H' '9' 'C' 'g' 'x' 'T' '6' 'e']
[[0 1 1 1 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 0 0 0 1 0 1 1 1 0]
 [1 0 0 0 1 1 0 0 0 1 1 0 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 0 0 0 1]
 [1 0 1 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1]
 [0 1 1 1 0 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0]
 [0 1 1 1 1 1 0 1 1 1 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 1 1]
 [0 1 1 1 0 1 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1]
 [1 1 1 1 1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0]
 [1 1 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 0]]


### Test-Train Split

We can to split our training data into two sets. One to train the neural network, and one to test the neural network.

In [55]:
# Import the train_test_split function from scikit-learn's model_selection module
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_dataset, y_dataset, test_size=0.1)

print(X_train.shape)
print(y_train.shape)



(900, 35)
(900,)


### Training

We can now train our model using the data we've generated. We use the `fit()` method to do this.

In [56]:
perceptron_model = Perceptron(max_iter=100)

perceptron_model.fit(X_train, y_train)

Perceptron(max_iter=100)

We can print out the paramters of our model

In [57]:
#  printing the learned weights (coefficients) of the Perceptron model
print("Weights (coefficients):")
print(perceptron_model.coef_)

# printing the learned bias (intercept) of the Perceptron model
print("Bias (intercept):")
print(perceptron_model.intercept_)

Weights (coefficients):
[[ 0. -1. -2. ... -2.  0. -1.]
 [-2.  4.  0. ... -2. -1. -4.]
 [-1.  0. -3. ...  1. -7. -2.]
 ...
 [-2.  0.  1. ... -4. -2.  2.]
 [ 0. -5. -3. ...  1.  2. -2.]
 [-4. -4. -2. ...  2.  0. -1.]]
Bias (intercept):
[  4. -10. -11.  -7.  -5.  -3. -10. -42.  -5. -14.  -5. -10. -33.  -5.
 -15. -14.  -5.  -7. -26.  -6.  -3.  -4.  -4. -12. -16.  -7.  -8.  -5.
 -19.  -7.  -4. -12.  -4. -10.  -5.  -3.  -3.  -6.  -6.  -5. -10.  -6.
  -2.  -7.  -5.  -3.  -3.  -7.  -8.  -4.  -1.  -4.  -5.  -3.  -2.  -3.
  -6.  -3.  -4.  -4.  -4.  -4.  -7.]


## Putting the Trained Neural Network into a GUI

We can now create our GUI and use the model!

In [58]:
# set up some display values
max_str_length = 10

# grid cell color
bgcolor_selected ='green'
bgcolor_unselected = 'black'

# grid size (7x5)
n_rows = 7
n_cols = 5

# create a text box to input a new string
text = widgets.Text(value='WELCOME',
                    placeholder='Type something',
                    description='Enter Here:',
                    disabled=False,
                    layout=Layout(width='50%', height='80px'))

# create a clear button to empty all grid cells
btn_clear = widgets.Button(description = 'Clear Matrix Display',
                           layout = Layout(width='50%', height='80px'))

# create a clear button to empty all grid cells
btn_display = widgets.Button(description = 'Show Original Matrix Display',
                             layout = Layout(width='50%', height='80px'))

# create a noisy button to empty all grid cells
btn_noise = widgets.Button(description = 'Show Noisy Matrix Display',
                           layout = Layout(width='50%', height='80px'))

# create a predict button
btn_predict = widgets.Button(description = 'Predict Noisy Matrix Display',
                             layout = Layout(width='50%', height='80px'))

# create a text area to display the prediction
prediction_box = widgets.Textarea(value='',
                                  placeholder='Perceptron Guesses...',
                                  description='',
                                  layout=widgets.Layout(height="120px", width="300px"))

# create a matrix for each character in text.value
chars = [np.zeros((n_rows, n_cols)) for i in range(max_str_length)]

# create a grid to accommodate 7 x 5 buttons 10 times
grid = [GridspecLayout(n_rows, n_cols, width='220px', layout=Layout(grid_gap='0px 0px')) for i in range(max_str_length)]

# create 7 x 5 buttons (each button denotes one pixel), again 10 times for the max_str_lenght
buttons = [[[widgets.Button(description = '',
                           layout = Layout(width='25px', height='25px', border='3px solid gray'))
                           for j in range(n_cols)] for i in range(n_rows)] for i in range(max_str_length)]

g2 = widgets.HBox([grid[i] for i in range(max_str_length)])

# colour the buttons as required
for k in range(max_str_length):
    for i in range(n_rows):
        for j in range(n_cols):
            if chars[k][i,j] == 1:
              buttons[k][i][j].style.button_color = bgcolor_selected
            else:
              buttons[k][i][j].style.button_color = bgcolor_unselected
            # this links the grid and buttons
            grid[k][i, j] = buttons[k][i][j]

# arrange our GUI elements
g1 = widgets.VBox([btn_display, btn_clear, btn_noise, btn_predict])
g3 = widgets.VBox([text,g1,g2,prediction_box])

# catching errors in the input:
def input_check(input):
    if len(input) > max_str_length:
      return 'Input too long, try again'
    for k in range(len(input)):
      if string_to_index(input[k]) == [999]:
        return 'Digit "' + input[k] + '" not recognised, try another input'
    else:
      return 'error'


def on_display_clicked():
    global chars
    # get the new matricies to display
    try:
      chars = string_to_matrix(text.value)
      for k in range(len(text.value)):
        for i in range(n_rows):
            for j in range(n_cols):
                if chars[k][i,j] == 1:
                  buttons[k][i][j].style.button_color = bgcolor_selected
                else:
                  buttons[k][i][j].style.button_color = bgcolor_unselected
    except:
      prediction_box.value = input_check(text.value)

# define what happens when display button is clicked
def on_btn_display_clicked(_):
    on_display_clicked()


# define what happens when the clear button is clicked
def on_btn_clear_clicked(_):
    global chars
    prediction_box.value = 'Perceptron Guesses...'
    chars = [np.zeros((n_rows, n_cols)) for i in range(max_str_length)]
    for k in range(max_str_length):
      for i in range(n_rows):
          for j in range(n_cols):
                buttons[k][i][j].style.button_color = bgcolor_unselected

def on_noise_clicked():
    global chars
    # get the new matricies to display
    try:
      chars = string_to_matrix(text.value)
      for k in range(len(text.value)):
        for i in range(n_rows):
            for j in range(n_cols):
                if chars[k][i,j] == 1:
                  buttons[k][i][j].style.button_color = bgcolor_selected
                elif np.random.choice([0,1],p=[9/10,1/10]) == 1:
                  chars[k][i,j] = 1
                  buttons[k][i][j].style.button_color = bgcolor_selected
                else:
                  buttons[k][i][j].style.button_color = bgcolor_unselected
    except:
      prediction_box.value = input_check(text.value)


def on_predict_clicked():

    try:
      # reshape chars to 2d
      data = np.asarray(chars)
      nsamples, nx, ny = data.shape
      chars_formatted = data.reshape((nsamples,nx*ny))

      # predict the outcome
      prediction = perceptron_model.predict(chars_formatted)

      # reformat as a string and output
      output = ''.join([str(elem) for elem in prediction])
      prediction_box.value = output
    except:
      prediction_box.value = input_check(text.value)

def on_btn_noise_clicked(_):
    on_noise_clicked()

def on_btn_predict_clicked(_):
    on_predict_clicked()

# bind the noise event to the noise button
btn_noise.on_click(on_btn_noise_clicked)

# bind the display event to the display button
btn_display.on_click(on_btn_display_clicked)

# bind the clear event to the clear button
btn_clear.on_click(on_btn_clear_clicked)

# bind the predict event to the predict button
btn_predict.on_click(on_btn_predict_clicked)

display(g3)

# Questions 2 and 3

View via [this](https://drive.google.com/file/d/13i7eH7OUaXBlLQpelFhl-KEkjUbL8-qw/view?usp=sharing) link.

In [59]:
!apt-get install poppler-utils

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
poppler-utils is already the newest version (22.02.0-2ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.


In [60]:
!pip install pdf2image

In [61]:
!pip uninstall gdown -y && pip install gdown
!gdown -V

Found existing installation: gdown 5.1.0
Uninstalling gdown-5.1.0:
  Successfully uninstalled gdown-5.1.0
  Using cached gdown-5.1.0-py3-none-any.whl (17 kB)
gdown 4.7.3 at /usr/local/lib/python3.10/dist-packages


We need the correct Google Drive link.

`https://drive.google.com/file/d/13i7eH7OUaXBlLQpelFhl-KEkjUbL8-qw/view?usp=sharing`

The key between `\d` and `\view` is `13i7eH7OUaXBlLQpelFhl-KEkjUbL8-qw`

So for a direct download,

https://drive.google.com/uc?export=download&id=13i7eH7OUaXBlLQpelFhl-KEkjUbL8-qw

In [62]:
!gdown https://drive.google.com/uc?export=download&id=13i7eH7OUaXBlLQpelFhl-KEkjUbL8-qw

Downloading...
From: https://drive.google.com/uc?export=download
To: /content/uc?export=download
1.69kB [00:00, 3.03MB/s]


In [63]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [64]:
from pdf2image import convert_from_path, convert_from_bytes
from IPython.display import display, Image

url = 'https://drive.google.com/uc?export=download&id=13i7eH7OUaXBlLQpelFhl-KEkjUbL8-qw'

images = convert_from_bytes(open('Neural_Computing_Coursework.pdf', 'rb').read(), size=800)
for i in range(len(images)):
  display(images[i])

FileNotFoundError: [Errno 2] No such file or directory: 'Neural_Computing_Coursework.pdf'

If this still isn't working, email me here: oliverkiranbrown@gmail.com and I'll send the file directly.
